version: "3.9"

services:
  app:
    image: ghcr.io/xintarius/restaurantdelivery_backend:develop
    container_name: restaurantdelivery_backend_web
    ports:
      - "3001:3001"
    command: bundle exec rails s -p 3001 -b 0.0.0.0
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  sidekiq:
    image: ghcr.io/xintarius/restaurantdelivery_backend:develop
    container_name: restaurantdelivery_backend_sidekiq
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: restaurantdelivery_backend_redis
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: